ci:
  autofix_prs: false

repos:
  - repo: https://github.com/astral-sh/ruff
    rev: 0.6.9
    hooks:
      - id: ruff
        args: ["format", "--diff", "src", "tests"]
      - id: ruff
        args: ["check", "--select", "I", "src", "tests"]

  - repo: https://github.com/PyCQA/doc8
    rev: 0.10.1
    hooks:
      - id: doc8
        additional_dependencies:
          - toml

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0
    hooks:
      - id: pretty-format-java
        args: [--autofix, --aosp]
        files: ^.*\.java$
